# -*- coding: utf-8 -*-
from extras_part2 import L, E

E['m7'] = L('Why were you late?',
 [('A', 'Why are you late again?', "Nega yana kechikdingiz?"),
  ('B', 'Because the bus broke down.', "Chunki avtobus buzilib qoldi."),
  ('A', 'So how did you get here?', "Unda bu yerga qanday keldingiz?"),
  ('B', 'I walked, so I am tired.', "Piyoda keldim, shuning uchun charchadim."),
  ('A', 'Although you are tired, you must finish the report.', "Charchagan bo'lsangiz ham, hisobotni tugatishingiz kerak."),
  ('B', 'I will do it, but I need a coffee first.', "Qilaman, lekin avval kofe kerak."),
  ('A', 'Fine. However, please call me next time.', "Mayli. Biroq keyingi safar menga qo'ng'iroq qiling."),
  ('B', 'I promise.', "Va'da beraman.")],
 [('Bog\'lovchilar: because, so, although', "because — chunki (sabab), so — shuning uchun (natija), although — garchi (qarama-qarshilik), however — biroq (yangi gap boshida).", [("I stayed at home because it was cold.", "Sovuq bo'lgani uchun uyda qoldim."), ("It was cold, so I stayed at home.", "Sovuq edi, shuning uchun uyda qoldim.")]),
  ('Vergul qoidasi', "so, but, however kabi bog'lovchilardan oldin (yoki keyin) vergul qo'yiladi. Because oldidan odatda vergul kerak emas.", [("He was ill, but he went to work.", "U kasal edi, lekin ishga bordi."), ("Although it rained, we walked.", "Yomg'ir yog'sa ham, biz yurdik.")])],
 ('A bad morning', "Yesterday morning my alarm did not ring, so I woke up late. I ran to the bus stop, but the bus had already left. Although I took a taxi, I arrived ten minutes late. My boss was not angry because I explained everything honestly.", "Kecha ertalab budilnikim jiringlamadi, shuning uchun kech uyg'ondim. Avtobus bekatiga yugurdim, lekin avtobus allaqachon ketgan edi. Taksi olgan bo'lsam ham, o'n daqiqa kech keldim. Boshlig'im jahli chiqmadi, chunki men hammasini rostgo'ylik bilan tushuntirdim.",
  [("Why did the writer wake up late?", "The alarm did not ring."), ("How did the writer get to work?", "By taxi."), ("Why was the boss not angry?", "Because the writer explained honestly.")]))

E['m8'] = L('Writing a polite email',
 [('A', 'I need to write an email to my manager.', "Menejerimga xat yozishim kerak."),
  ('B', 'Start with "Dear Mr. Smith".', "'Dear Mr. Smith' bilan boshlang."),
  ('A', 'Should I write "Hi" instead?', "'Hi' deb yozsam bo'ladimi?"),
  ('B', 'No, that is too informal for a manager.', "Yo'q, bu menejer uchun juda norasmiy."),
  ('A', 'How do I finish the email?', "Xatni qanday tugatay?"),
  ('B', 'Use "Kind regards" or "Yours sincerely".', "'Kind regards' yoki 'Yours sincerely' yozing."),
  ('A', 'Thanks, that sounds professional.', "Rahmat, bu kasbiy ko'rinadi."),
  ('B', 'Do not forget to check your spelling.', "Imloni tekshirishni unutmang.")],
 [('Rasmiy va norasmiy so\'zlar', "Norasmiy: get, buy, ask for, a lot of. Rasmiy: obtain, purchase, request, numerous. Rasmiy yozuvda qisqartmalar (don't, I'm) ishlatilmaydi.", [("I would be grateful if you could help me.", "Yordam bersangiz, minnatdor bo'lardim."), ("Can you help me?", "Menga yordam bera olasizmi? (norasmiy)")]),
  ('Mashhur idiomalar', "a piece of cake — juda oson; break the ice — muzni eritmoq; once in a blue moon — juda kamdan-kam. Idiomani so'zma-so'z tarjima qilmang.", [("The exam was a piece of cake.", "Imtihon juda oson edi."), ("He visits us once in a blue moon.", "U bizni juda kamdan-kam ziyorat qiladi.")])],
 ('My first job application', "Last month I applied for my first job. I wrote a formal letter and attached my CV. I used polite phrases such as 'I am writing to apply' and 'I look forward to hearing from you'. A week later the company invited me for an interview.", "O'tgan oy birinchi ishimga ariza berdim. Rasmiy xat yozib, rezyumemni biriktirdim. 'Murojaat qilish uchun yozyapman' va 'Javobingizni kutaman' kabi xushmuomala iboralardan foydalandim. Bir haftadan keyin kompaniya meni suhbatga taklif qildi.",
  [("What did the writer attach to the letter?", "A CV."), ("What polite phrase did the writer use?", "I look forward to hearing from you."), ("What happened a week later?", "The company invited the writer for an interview.")]))

E['m9'] = L('Choosing a career',
 [('A', 'What do you want to be in the future?', "Kelajakda kim bo'lmoqchisiz?"),
  ('B', 'In my opinion, teaching is a noble job.', "Mening fikrimcha, o'qituvchilik olijanob kasb."),
  ('A', 'I agree, but the salary is low.', "Roziman, lekin maosh past."),
  ('B', 'That is true, yet I prefer a job that helps people.', "To'g'ri, lekin men odamlarga yordam beradigan ishni afzal ko'raman."),
  ('A', 'As for me, I would like to be an engineer.', "Menga kelsak, men muhandis bo'lishni xohlayman."),
  ('B', 'Why do you think so?', "Nega bunday deb o'ylaysiz?"),
  ('A', 'I think it is creative and well paid.', "Menimcha, bu ijodiy va yaxshi haq to'lanadigan kasb."),
  ('B', 'Both jobs are important for society.', "Ikkala kasb ham jamiyat uchun muhim.")],
 [('Fikr bildirish', "In my opinion... (fikrimcha), I think / I believe... (o'ylaymanki), As far as I am concerned... (menga kelsak). Rozilik: I agree, Exactly. Norozilik: I do not agree, I see it differently.", [("I believe that reading is important.", "Menimcha, o'qish muhim."), ("I see it differently.", "Men buni boshqacha ko'raman.")]),
  ('Sabab va izoh so\'rash', "Why do you think so? — Nega unday deb o'ylaysiz? For example, / For instance, — masalan. Fikringizni misol bilan quvvatlang.", [("For example, many people work from home.", "Masalan, ko'p odamlar uydan ishlaydi."), ("That is why I agree.", "Shuning uchun men roziman.")])],
 ('Two cultures, one world', "My friend is from Japan and I am from Uzbekistan. Our cultures are different, but we have a lot in common. In both countries people respect their elders and love tea. When I visited her family, I learned to eat with chopsticks. She learned to bake bread in a tandoor.", "Do'stim Yaponiyadan, men O'zbekistondanman. Madaniyatlarimiz har xil, lekin umumiy jihatlarimiz ko'p. Ikkala mamlakatda ham odamlar kattalarni hurmat qiladi va choyni yaxshi ko'radi. Uning oilasiga borganimda tayoqcha bilan ovqatlanishni o'rgandim. U tandirda non yopishni o'rgandi.",
  [("Where is the writer's friend from?", "From Japan."), ("What do both countries love?", "Tea (and respect for elders)."), ("What did the friend learn?", "To bake bread in a tandoor.")]))

E['m25'] = L('Choosing a university',
 [('A', 'Which university do you want to enter?', "Qaysi universitetga kirmoqchisiz?"),
  ('B', 'I want to enter the one that has a good IT faculty.', "Yaxshi IT fakulteti bor universitetga kirmoqchiman."),
  ('A', 'Is it the university which is near the metro?', "Metro yaqinidagi universitetmi?"),
  ('B', 'Yes, that is the one I mean.', "Ha, men aytayotgan o'sha."),
  ('A', 'Do you have to take an entrance exam?', "Kirish imtihonini topshirishingiz kerakmi?"),
  ('B', 'Yes, because the competition is high.', "Ha, chunki tanlov katta."),
  ('A', 'I am sure you will pass.', "Ishonchim komil, o'tasiz."),
  ('B', 'I hope so. I am studying every day.', "Umid qilaman. Har kuni tayyorlanyapman.")],
 [('Nisbiy olmoshlar: who, which, that', "who — odamlar uchun, which — narsalar uchun, that — ikkalasi uchun. Ular gapga ma'lumot qo'shadi: The teacher who teaches us is kind.", [("The book that I read was interesting.", "Men o'qigan kitob qiziqarli edi."), ("The student who won is my friend.", "G'olib bo'lgan talaba mening do'stim.")]),
  ('Because va because of', "because + gap (because it rained), because of + ot (because of the rain). Ikkalasi ham 'sababli' degani, lekin tuzilishi boshqa.", [("We stayed home because of the storm.", "Bo'ron sababli uyda qoldik."), ("We stayed home because there was a storm.", "Bo'ron bo'lgani uchun uyda qoldik.")])],
 ('Student life', "University life is very different from school. Students choose their own subjects and decide how to spend their time. There are many clubs, which help people to find friends. The most important thing is to study regularly, because exams are serious.", "Universitet hayoti maktabdan juda farq qiladi. Talabalar o'z fanlarini tanlaydi va vaqtini o'zi taqsimlaydi. Ko'plab to'garaklar bor, ular do'st topishga yordam beradi. Eng muhimi — muntazam o'qish, chunki imtihonlar jiddiy.",
  [("What do students choose?", "Their own subjects."), ("What do clubs help people to do?", "Find friends."), ("What is the most important thing?", "To study regularly.")]))

E['m26'] = L('Saving the environment',
 [('A', 'Have you heard about the new recycling project?', "Yangi qayta ishlash loyihasi haqida eshitdingizmi?"),
  ('B', 'Yes. People living in our street collect plastic.', "Ha. Ko'chamizda yashovchilar plastik yig'adi."),
  ('A', 'Walking to work also helps nature.', "Ishga piyoda borish ham tabiatga yordam beradi."),
  ('B', 'True. Cars produce a lot of smoke.', "To'g'ri. Mashinalar ko'p tutun chiqaradi."),
  ('A', 'Having planted fifty trees, our class won a prize.', "Ellikta daraxt ekib, sinfimiz sovrin yutdi."),
  ('B', 'Congratulations! Trees give us clean air.', "Tabriklayman! Daraxtlar bizga toza havo beradi."),
  ('A', 'We must protect nature for the next generation.', "Kelajak avlod uchun tabiatni asrashimiz kerak."),
  ('B', 'I completely agree.', "Men butunlay qo'shilaman.")],
 [('Participle iboralar: -ing', "-ing sifatdosh asosiy gapga qisqa ma'lumot qo'shadi: The man standing there is my uncle (= who is standing). Walking home, I met a friend (= While I was walking...).", [("The girl sitting by the window is my sister.", "Deraza yonida o'tirgan qiz mening singlim."), ("Feeling tired, he went to bed.", "Charchagan holda u uxlashga yotdi.")]),
  ('-ed sifatdosh', "-ed (yoki 3-shakl) sifatdosh majhul ma'no beradi: a broken window (sindirilgan oyna), the book written by Tolstoy (Tolstoy yozgan kitob).", [("The trees planted last year are growing.", "O'tgan yili ekilgan daraxtlar o'syapti."), ("A lost key", "yo'qolgan kalit")])],
 ('Our green planet', "Our planet is facing serious problems: pollution, climate change and the loss of forests. Governments must act, but each person can help too. Using less plastic, saving water and planting trees are simple steps. If everybody does a little, the result will be big.", "Sayyoramiz jiddiy muammolarga duch kelmoqda: ifloslanish, iqlim o'zgarishi va o'rmonlarning kamayishi. Hukumatlar harakat qilishi kerak, lekin har bir inson ham yordam bera oladi. Kamroq plastik ishlatish, suvni tejash va daraxt ekish — oddiy qadamlar. Agar hamma ozgina qilsa, natija katta bo'ladi.",
  [("What problems does the planet face?", "Pollution, climate change, loss of forests."), ("Who must act?", "Governments (and each person too)."), ("Name one simple step.", "Using less plastic / saving water / planting trees.")]))

E['m27'] = L('Did you read the news?',
 [('A', 'Did you read the news this morning?', "Bugun ertalab yangiliklarni o'qidingizmi?"),
  ('B', 'Yes. The article said that the economy was growing.', "Ha. Maqolada iqtisodiyot o'syapti deyilgan edi."),
  ('A', 'The reporter told us that it would continue.', "Muxbir bu davom etishini aytdi."),
  ('B', 'I asked my father if he trusted the news.', "Otamdan yangiliklarga ishonasizmi, deb so'radim."),
  ('A', 'What did he answer?', "U nima deb javob berdi?"),
  ('B', 'He said that he checked several sources.', "U bir necha manbani tekshirishini aytdi."),
  ('A', 'That is a wise habit.', "Bu dono odat."),
  ('B', 'Yes, fake news spreads quickly.', "Ha, yolg'on xabarlar tez tarqaladi.")],
 [('Reported speech: zamon siljishi', "Gapni boshqa odamga uzatganda zamon bir pog'ona orqaga suriladi: am/is → was, will → would, go → went. 'I am tired' → He said that he was tired.", [("She said, 'I like music.' → She said that she liked music.", "U musiqani yoqtirishini aytdi."), ("'I will come.' → He said he would come.", "U kelishini aytdi.")]),
  ('Savollarni uzatish', "Ha/yo'q savollarda if/whether, so'z savollarda savol so'zi ishlatiladi, tartib darak gap kabi bo'ladi: He asked where I lived.", [("She asked if I was ready.", "U tayyormisiz deb so'radi."), ("They asked where we were going.", "Ular qayerga ketyapmiz deb so'rashdi.")])],
 ('Media in our lives', "Every day we get news from television, newspapers and the internet. Social media is fast, but it is not always reliable. A good reader always asks: who wrote this and why? Teachers say that checking two or three sources is the best way to avoid fake news.", "Har kuni yangiliklarni televizor, gazeta va internetdan olamiz. Ijtimoiy tarmoqlar tez, lekin har doim ishonchli emas. Yaxshi o'quvchi doim so'raydi: buni kim yozgan va nega? O'qituvchilar yolg'on xabardan qochishning eng yaxshi yo'li — ikki-uch manbani tekshirish, deydi.",
  [("Where do we get news?", "From TV, newspapers and the internet."), ("Is social media always reliable?", "No, it is not."), ("What is the best way to avoid fake news?", "Checking two or three sources.")]))

E['m28'] = L('At the museum',
 [('A', 'This painting looks like a photograph.', "Bu rasm fotosuratga o'xshaydi."),
  ('B', 'It looks as if the artist used a camera!', "Go'yo rassom kameradan foydalangandek!"),
  ('A', 'I prefer abstract art, to be honest.', "Rostini aytsam, men abstrakt san'atni afzal ko'raman."),
  ('B', 'Really? To me it seems like a mess of colours.', "Rostdanmi? Menga u ranglar g'ovlashiga o'xshaydi."),
  ('A', 'Art is not the same as science; there is no single answer.', "San'at fan bilan bir xil emas; yagona javob yo'q."),
  ('B', 'You are right. Who is your favourite writer?', "To'g'ri aytasiz. Sevimli yozuvchingiz kim?"),
  ('A', 'Abdulla Qodiriy. His novels are unforgettable.', "Abdulla Qodiriy. Uning romanlari unutilmas."),
  ('B', 'I agree. I read "O\'tgan kunlar" twice.', "Qo'shilaman. Men 'O'tgan kunlar'ni ikki marta o'qidim.")],
 [('like, as, as if', "like + ot: She sings like a bird. as if / as though + gap: He talks as if he knew everything. the same as — bilan bir xil; different from — dan farqli.", [("He runs like the wind.", "U shamoldek yuguradi."), ("It looks as if it is going to rain.", "Yomg'ir yog'adiganga o'xshaydi.")]),
  ('San\'at haqida gapirish', "masterpiece (durdona), exhibition (ko'rgazma), portrait (portret), landscape (manzara), novel (roman), poet (shoir). Fikr: It reminds me of... (menga ... ni eslatadi).", [("This poem reminds me of my childhood.", "Bu she'r menga bolaligimni eslatadi."), ("We visited an art exhibition.", "Biz san'at ko'rgazmasiga bordik.")])],
 ('The power of books', "A good book can change your life. It teaches you new things, shows other worlds and helps you understand people. My grandfather says that a house without books is like a body without a soul. Now I try to read at least twenty pages every day.", "Yaxshi kitob hayotingizni o'zgartirishi mumkin. U sizga yangi narsalarni o'rgatadi, boshqa olamlarni ko'rsatadi va odamlarni tushunishga yordam beradi. Bobom kitobsiz uy ruhsiz tanaga o'xshaydi, deydi. Hozir men har kuni kamida yigirma bet o'qishga harakat qilaman.",
  [("What can a good book do?", "Change your life."), ("What does the grandfather say?", "A house without books is like a body without a soul."), ("How many pages does the writer try to read daily?", "At least twenty.")]))
