# -*- coding: utf-8 -*-
from extras_part1 import L, E

E['m4'] = L('A weekend in the mountains',
 [('A', 'Did you go anywhere last weekend?', "O'tgan dam olish kunlari biror joyga bordingizmi?"),
  ('B', 'Yes, we went to the mountains.', "Ha, biz tog'ga bordik."),
  ('A', 'How did you travel?', "Qanday bordingiz?"),
  ('B', 'We took a bus and then walked for three hours.', "Avtobusga o'tirdik, keyin uch soat piyoda yurdik."),
  ('A', 'Did you take photos?', "Rasmga oldingizmi?"),
  ('B', 'Of course. I took more than a hundred.', "Albatta. Yuztadan ko'p rasmga oldim."),
  ('A', 'Was the weather good?', "Ob-havo yaxshi edimi?"),
  ('B', 'It was sunny, but a little cold.', "Quyoshli, lekin biroz sovuq edi.")],
 [('Muntazam fe\'llar: -ed', "Muntazam fe'llarga -ed qo'shiladi: work → worked, play → played. -e bilan tugasa faqat -d: live → lived. Undosh+y: study → studied.", [("We visited our aunt.", "Biz xolamnikiga bordik."), ("She studied all night.", "U tun bo'yi o'qidi.")]),
  ('Inkor va savol: did', "Past Simple da inkor va savolda did / did not ishlatiladi, asosiy fe'l asl holida qoladi: Did you go? I did not go. Bu qoidani 'went' kabi nomuntazam fe'llarga ham qo'llang.", [("I did not see him yesterday.", "Men uni kecha ko'rmadim."), ("Did they come late?", "Ular kech keldimi?")])],
 ('A trip to Chimgan', "Last summer my friends and I visited Chimgan. We left early in the morning and arrived at ten. We walked along a river and ate lunch on the grass. In the afternoon it rained a little, so we returned to the bus. It was a tiring but wonderful day.", "O'tgan yozda do'stlarim va men Chimyonga bordik. Ertalab erta chiqib, soat o'nda yetib keldik. Daryo bo'ylab yurdik va maysada tushlik qildik. Tushdan keyin ozgina yomg'ir yog'di, shuning uchun avtobusga qaytdik. Bu charchatadigan, lekin ajoyib kun edi.",
  [("When did they arrive?", "At ten."), ("What did they do at lunchtime?", "They ate lunch on the grass."), ("Why did they return to the bus?", "Because it rained.")]))

E['m5'] = L('Plans for next year',
 [('A', 'What are you going to do next year?', "Kelasi yil nima qilmoqchisiz?"),
  ('B', 'I am going to study English in London.', "Men Londonda ingliz tilini o'rganmoqchiman."),
  ('A', 'Will it be expensive?', "Qimmat bo'ladimi?"),
  ('B', 'I think it will be more expensive than here.', "O'ylaymanki, bu yerdagidan qimmatroq bo'ladi."),
  ('A', 'Will you work there?', "U yerda ishlaysizmi?"),
  ('B', 'Maybe. I will look for a part-time job.', "Balki. Yarim kunlik ish qidiraman."),
  ('A', 'I am sure you will do well.', "Ishonchim komilki, siz yaxshi uddalaysiz."),
  ('B', 'Thank you, that is very kind.', "Rahmat, bu juda yaxshi gap.")],
 [('will va going to', "'Going to' — oldindan qilingan reja yoki ko'rinib turgan belgi: I am going to study. 'Will' — o'sha payt qabul qilingan qaror, bashorat, va'da: I will help you.", [("Look at the clouds! It is going to rain.", "Bulutlarga qarang! Yomg'ir yog'adi."), ("I will call you tonight.", "Men sizga bugun kechqurun qo'ng'iroq qilaman.")]),
  ('Qiyosiy va orttirma daraja', "Qisqa sifat: tall → taller → the tallest. Uzun sifat: more/most beautiful. Qoidasiz: good → better → the best, bad → worse → the worst.", [("This book is more interesting than that one.", "Bu kitob anavidan qiziqarliroq."), ("He is the best player in the team.", "U jamoadagi eng yaxshi o'yinchi.")])],
 ('My plan for the future', "In five years I want to be a doctor. First I will finish school, then I will enter the medical university. It will be difficult, but I am going to work hard. My father says that a good doctor is the happiest person in the world.", "Besh yildan keyin men shifokor bo'lishni xohlayman. Avval maktabni tugataman, keyin tibbiyot universitetiga kiraman. Bu qiyin bo'ladi, lekin men qattiq mehnat qilmoqchiman. Dadam yaxshi shifokor dunyodagi eng baxtli odam, deydi.",
  [("What does the writer want to be?", "A doctor."), ("What will he/she do first?", "Finish school."), ("What does the father say?", "A good doctor is the happiest person in the world.")]))

E['m6'] = L('Where is it?',
 [('A', 'Excuse me, where is the post office?', "Kechirasiz, pochta qayerda?"),
  ('B', 'It is between the bank and the pharmacy.', "U bank va dorixona o'rtasida."),
  ('A', 'Is it far from here?', "Bu yerdan uzoqmi?"),
  ('B', 'No, it is opposite the park.', "Yo'q, parkning qarshisida."),
  ('A', 'Thank you. And the bus stop?', "Rahmat. Avtobus bekati-chi?"),
  ('B', 'It is behind that building, next to the cafe.', "U anavi bino orqasida, kafening yonida."),
  ('A', 'Great, I see it now.', "Zo'r, endi ko'rdim."),
  ('B', 'You are welcome.', "Arzimaydi.")],
 [('Joy predloglari', "in front of (oldida), behind (orqasida), next to / beside (yonida), between (o'rtasida), opposite (qarshisida), under (ostida), above (tepasida).", [("The cat is under the table.", "Mushuk stol ostida."), ("The school is opposite the library.", "Maktab kutubxonaning qarshisida.")]),
  ('Harakat predloglari', "to (...ga), from (...dan), into (ichiga), out of (ichidan), across (kesib), through (orqali), along (bo'ylab).", [("We walked across the bridge.", "Biz ko'prikdan o'tdik."), ("He went into the room.", "U xonaga kirdi.")])],
 ('My neighbourhood', "My neighbourhood is quiet and green. There is a small park in front of my house, and a bakery next to it. Behind the bakery there is a school. Every morning I walk through the park to the bus stop, which is opposite the pharmacy.", "Mening mahallam sokin va ko'm-ko'k. Uyim oldida kichik park, uning yonida novvoyxona bor. Novvoyxona orqasida maktab bor. Har ertalab men park orqali dorixona qarshisidagi avtobus bekatiga yuraman.",
  [("What is in front of the house?", "A small park."), ("What is behind the bakery?", "A school."), ("Where is the bus stop?", "Opposite the pharmacy.")]))

E['m21'] = L('Planning a picnic',
 [('A', 'What is the weather like today?', "Bugun ob-havo qanday?"),
  ('B', 'It is sunny and warm.', "Quyoshli va iliq."),
  ('A', 'Let us have a picnic then!', "Unda pikniklik qilaylik!"),
  ('B', 'Good idea. But the forecast says it will rain tomorrow.', "Yaxshi fikr. Lekin prognozda ertaga yomg'ir yog'adi deyilgan."),
  ('A', 'Then we must go today.', "Unda bugun borishimiz kerak."),
  ('B', 'I will bring a blanket and some sandwiches.', "Men ko'rpacha va sendvichlar olib kelaman."),
  ('A', 'I will take juice and fruit.', "Men sharbat va meva olaman."),
  ('B', 'Perfect. Let us meet at noon.', "Ajoyib. Peshinda uchrashamiz.")],
 [('Ob-havo ifodalari', "Ob-havoda 'it' rasmiy ega bo'lib ishlaydi: It is raining, It is cold, It snows in winter. 'What is the weather like?' — ob-havo qanday?", [("It is windy today.", "Bugun shamol bor."), ("It never snows in July.", "Iyulda hech qachon qor yog'maydi.")]),
  ('Present Continuous', "Hozir davom etayotgan ish: am/is/are + fe'l-ing. Ob-havoda ham ishlatiladi: It is raining now.", [("The sun is shining.", "Quyosh charaqlayapti."), ("Are the children playing outside?", "Bolalar tashqarida o'ynayaptimi?")])],
 ('Four seasons', "In my country there are four seasons. Spring is green and fresh. Summer is very hot, and we eat a lot of watermelon. Autumn is rainy and golden. Winter is cold, and sometimes it snows. My favourite season is autumn because the weather is mild.", "Mening mamlakatimda to'rt fasl bor. Bahor yam-yashil va salqin. Yoz juda issiq, biz ko'p tarvuz yeymiz. Kuz yomg'irli va oltin rangda. Qish sovuq, ba'zan qor yog'adi. Sevimli faslim kuz, chunki havo mo''tadil.",
  [("How many seasons are there?", "Four."), ("What do people eat in summer?", "A lot of watermelon."), ("Why does the writer like autumn?", "Because the weather is mild.")]))

E['m22'] = L('Taking a taxi',
 [('Driver', 'Where to, madam?', "Qayerga, xonim?"),
  ('Guest', 'To the railway station, please.', "Temir yo'l vokzaliga, iltimos."),
  ('Driver', 'It takes about twenty minutes.', "Taxminan yigirma daqiqa ketadi."),
  ('Guest', 'Turn left at the traffic lights, please.', "Svetoforda chapga buring, iltimos."),
  ('Driver', 'Sure. Then straight on?', "Albatta. Keyin to'g'riga-mi?"),
  ('Guest', 'Yes, go straight and stop at the corner.', "Ha, to'g'riga yuring va burchakda to'xtang."),
  ('Driver', 'Here we are. That is fifteen thousand.', "Yetib keldik. O'n besh ming."),
  ('Guest', 'Here you are. Keep the change.', "Marhamat. Qaytimi sizniki.")],
 [('Buyruq mayli inkori', "Inkor buyruq: Do not (Don't) + fe'l. Taklif uchun: Let's + fe'l. Xushmuomalalik uchun please qo'shing.", [("Don't turn right here.", "Bu yerda o'ngga burilmang."), ("Let's take a taxi.", "Taksi olaylik.")]),
  ('Yo\'nalish so\'zlari', "turn left/right (chapga/o'ngga buring), go straight on (to'g'riga yuring), at the corner (burchakda), at the traffic lights (svetoforda), take the second street (ikkinchi ko'chaga buriling).", [("Take the second street on the right.", "O'ng tomondagi ikkinchi ko'chaga buriling."), ("Go past the bank.", "Bankdan o'tib keting.")])],
 ('Lost in the city', "Last week I was lost in a big city. I asked a policeman for help. He said: go straight on, turn right at the second street, and you will see the museum on your left. I thanked him and followed his directions. In ten minutes I was at my hotel.", "O'tgan hafta men katta shaharda adashib qoldim. Politsiyachidan yordam so'radim. U dedi: to'g'riga yuring, ikkinchi ko'chadan o'ngga buriling, chap tomoningizda muzey ko'rinadi. Men unga rahmat aytdim va ko'rsatmasiga amal qildim. O'n daqiqada mehmonxonamda edim.",
  [("Who did the writer ask for help?", "A policeman."), ("Where did he say to turn?", "Right at the second street."), ("How long did it take to reach the hotel?", "Ten minutes.")]))

E['m23'] = L('Hobbies and sport',
 [('A', 'What do you do in your free time?', "Bo'sh vaqtingizda nima qilasiz?"),
  ('B', 'I like playing football with my friends.', "Men do'stlarim bilan futbol o'ynashni yaxshi ko'raman."),
  ('A', 'How often do you play?', "Qanchalik tez-tez o'ynaysiz?"),
  ('B', 'Twice a week, on Tuesday and Saturday.', "Haftasiga ikki marta, seshanba va shanba kuni."),
  ('A', 'I enjoy swimming, but I hate running.', "Men suzishni yoqtiraman, lekin yugurishni yomon ko'raman."),
  ('B', 'Really? Running is good for health.', "Rostdanmi? Yugurish sog'liq uchun foydali."),
  ('A', 'I know, but I prefer the pool.', "Bilaman, lekin men basseynni afzal ko'raman."),
  ('B', 'Then let us go swimming together!', "Unda birga suzishga boraylik!")],
 [('Like / love / hate + -ing', "Yoqtirish va yoqtirmaslikni bildiruvchi fe'llardan keyin fe'l -ing shaklida keladi: like reading, love swimming, hate waking up early.", [("She loves dancing.", "U raqsga tushishni yaxshi ko'radi."), ("I do not like cooking.", "Men ovqat pishirishni yoqtirmayman.")]),
  ('How often? — takrorlanish', "once a week (haftada bir marta), twice a month (oyda ikki marta), three times a year (yilda uch marta). Savol: How often do you...?", [("I go to the gym three times a week.", "Men haftasiga uch marta sport zaliga boraman."), ("How often does he play chess?", "U qanchalik tez-tez shaxmat o'ynaydi?")])],
 ('My favourite sport', "My favourite sport is basketball. I play it with my classmates after school. We have a small team, and we play in the yard twice a week. Sport makes me strong and helps me make new friends. I want to join a real club next year.", "Mening sevimli sportim basketbol. Men uni maktabdan keyin sinfdoshlarim bilan o'ynayman. Bizning kichik jamoamiz bor va haftasiga ikki marta hovlida o'ynaymiz. Sport meni kuchli qiladi va yangi do'stlar orttirishga yordam beradi. Kelasi yil haqiqiy klubga a'zo bo'lmoqchiman.",
  [("What is the writer's favourite sport?", "Basketball."), ("How often do they play?", "Twice a week."), ("What does the writer want to do next year?", "Join a real club.")]))

E['m24'] = L('Trying on clothes',
 [('Seller', 'Can I help you?', "Sizga yordam bera olamanmi?"),
  ('Buyer', 'Yes, I am looking for a jacket.', "Ha, men kurtka qidiryapman."),
  ('Seller', 'What size do you wear?', "Qaysi o'lchamni kiyasiz?"),
  ('Buyer', 'Medium. Can I try this one on?', "O'rtacha. Buni kiyib ko'rsam bo'ladimi?"),
  ('Seller', 'Of course. The fitting room is over there.', "Albatta. Primerka xonasi anavi yerda."),
  ('Buyer', 'It is too small. Do you have a bigger one?', "Kichik ekan. Kattaroq bor-mi?"),
  ('Seller', 'Yes, this one is larger and cheaper.', "Ha, bu kattaroq va arzonroq."),
  ('Buyer', 'Great, I will take it.', "Zo'r, buni olaman.")],
 [('Too va enough', "too + sifat = ortiqcha (too small — juda kichik, yaramaydi). sifat + enough = yetarli (big enough — yetarlicha katta).", [("These shoes are too tight.", "Bu poyabzal juda tor."), ("The coat is warm enough.", "Palto yetarlicha issiq.")]),
  ('Kiyim fe\'llari', "wear — kiyib yurmoq, put on — kiymoq, try on — kiyib ko'rmoq, take off — yechmoq. Bularni adashtirmang.", [("I put on my coat and went out.", "Men paltoni kiyib, tashqariga chiqdim."), ("Take off your shoes, please.", "Poyabzalingizni yechting, iltimos.")])],
 ('Shopping online', "Today many people buy clothes online. It is easy and quick, and the prices are often lower. But there is a problem: you cannot try things on. My sister bought a dress that was too long, so she sent it back. Now she always checks the size chart carefully.", "Bugun ko'p odamlar kiyimni internetdan sotib oladi. Bu oson va tez, narxlar ko'pincha past. Lekin muammo bor: kiyib ko'rib bo'lmaydi. Singlim juda uzun ko'ylak sotib oldi va uni qaytarib yubordi. Endi u doim o'lchamlar jadvalini sinchiklab tekshiradi.",
  [("Why do people buy clothes online?", "It is easy, quick and cheaper."), ("What was the problem with the dress?", "It was too long."), ("What does the sister do now?", "She checks the size chart carefully.")]))
